In [1]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [2]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [3]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [4]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [5]:
print(type(iris))
print(type(digits))

<class 'sklearn.utils.Bunch'>
<class 'sklearn.utils.Bunch'>


In [6]:
from sklearn import svm

In [7]:
clf = svm.SVC(gamma=0.001, C=100.)

In [8]:
clf.fit(digits.data[:-1], digits.target[:-1])


SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [9]:
clf.predict(digits.data[-1:])

array([8])

In [10]:
clf = svm.SVC()

In [11]:
X, y = iris.data, iris.target

In [12]:
clf.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
import pickle

In [14]:
s = pickle.dumps(clf)

In [15]:
clf2 = pickle.loads(s)

In [16]:
clf2.predict(X[0:1])

array([0])

In [17]:
y[0]

0

In [18]:
from sklearn.externals import joblib

In [19]:
joblib.dump(clf, 'filename.pkl')

['filename.pkl']

In [20]:
clf = joblib.load('filename.pkl')

In [21]:
import numpy as np

In [22]:
from sklearn import random_projection

In [23]:
rng = np.random.RandomState(0)

In [24]:
X = rng.rand(10, 2000)

In [25]:
X = np.array(X, dtype='float32')

In [26]:
X.dtype

dtype('float32')

In [27]:
transformer = random_projection.GaussianRandomProjection()
X_new = transformer.fit_transform(X)

In [28]:
X_new.dtype

dtype('float64')

In [29]:
from sklearn.svm import SVC

In [30]:
clf = SVC()

In [31]:
clf.fit(iris.data, iris.target)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [32]:
list(clf.predict(iris.data[:3]))

[0, 0, 0]

In [33]:
clf.fit(iris.data, iris.target_names[iris.target])

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [34]:
list(clf.predict(iris.data[:3]))

['setosa', 'setosa', 'setosa']

In [35]:
rng = np.random.RandomState(0)

In [36]:
X = rng.rand(100, 10)

In [37]:
y = rng.binomial (1, .5, 100)

In [38]:
X_test = rng.rand(5, 10)

In [39]:
clf = SVC()

In [40]:
clf.set_params(kernel='linear').fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [41]:
clf.predict(X_test)

array([1, 0, 1, 1, 0])

In [42]:
 clf.set_params(kernel='rbf').fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [43]:
clf.predict(X_test)

array([0, 0, 0, 1, 0])

In [44]:
from sklearn.multiclass import OneVsRestClassifier

In [45]:
from sklearn.preprocessing import LabelBinarizer

In [46]:
X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]

In [47]:
y = [0, 0, 1, 1, 2]


In [48]:
classif = OneVsRestClassifier(estimator=SVC(random_state=0))

In [49]:
classif.fit(X, y).predict(X)

array([0, 0, 1, 1, 2])

In [50]:
y = LabelBinarizer().fit_transform(y)

In [51]:
classif.fit(X, y).predict(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
 from sklearn.preprocessing import MultiLabelBinarizer

In [53]:
y = [[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]

In [54]:
y = MultiLabelBinarizer().fit_transform(y)

In [55]:
classif.fit(X, y).predict(X)

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])

In [56]:
# End of introductory tutorial

In [57]:
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']

In [58]:
from sklearn.datasets import fetch_20newsgroups

In [59]:
twenty_train = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)

In [60]:
twenty_train.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [61]:
len(twenty_train.data)

2257

In [62]:
len(twenty_train.filenames)

2257

In [63]:
print("\n".join(twenty_train.data[2].split("\n")[:3]))

From: djohnson@cs.ucsd.edu (Darin Johnson)
Subject: Re: harrassed at work, could use some prayers
Organization: =CSE Dept., U.C. San Diego


In [64]:
print(twenty_train.target_names[twenty_train.target[2]])

soc.religion.christian


In [65]:
twenty_train.target[:10]

array([1, 1, 3, 3, 3, 3, 3, 2, 2, 2], dtype=int64)

In [66]:
for t in twenty_train.target[:10]:print(twenty_train.target_names[t])

comp.graphics
comp.graphics
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
sci.med
sci.med
sci.med


In [67]:
twenty_train.data[68]

'From: revdak@netcom.com (D. Andrew Kille)\nSubject: Re: Easter: what\'s in a name? (was Re: New Testament Double Stan\nOrganization: NETCOM On-line Communication Services (408 241-9760 guest)\nLines: 40\n\nDaniel Segard (dsegard@nyx.cs.du.edu) wrote:\n\n[a lot of stuff deleted]\n\n:      For that matter, stay Biblical and call it Omar Rasheet (The Feast of\n: First Fruits).  Torah commands that this be observed on the day following\n: the Sabbath of Passover week.  (Sunday by any other name in modern\n: parlance.)  Why is there so much objection to observing the Resurrection\n: on the 1st day of the week on which it actually occured?  Why jump it all\n: over the calendar the way Easter does?  Why not just go with the Sunday\n: following Passover the way the Bible has it?  Why seek after unbiblical\n: methods?\n:  \nIn fact, that is the reason Easter "jumps all over the calendar"- Passsover\nitself is a lunar holiday, not a solar one, and thus falls over a wide\npossible span of times.

In [68]:
from sklearn.feature_extraction.text import CountVectorizer

In [69]:
count_vect = CountVectorizer()

In [70]:
X_train_counts = count_vect.fit_transform(twenty_train.data)

In [71]:
X_train_counts.shape

(2257, 35788)

In [72]:
 count_vect.vocabulary_.get(u'algorithm')

4690

In [73]:
# yo that's dope

In [74]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape

(2257, 35788)

In [75]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

(2257, 35788)

In [76]:
from sklearn.naive_bayes import MultinomialNB

In [77]:
clf = MultinomialNB().fit(X_train_tfidf, twenty_train.target)

In [78]:
docs_new = ['God is love', 'OpenGL on the GPU is fast']

In [79]:
X_new_counts = count_vect.transform(docs_new)

In [80]:
X_new_tfidf = tfidf_transformer.transform(X_new_counts)

In [81]:
predicted = clf.predict(X_new_tfidf)

In [82]:
for doc, category in zip(docs_new, predicted):
    print('%r => %s' % (doc, twenty_train.target_names[category]))

'God is love' => soc.religion.christian
'OpenGL on the GPU is fast' => comp.graphics


In [83]:
from sklearn.pipeline import Pipeline

In [84]:
text_clf = Pipeline([('vect', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('clf', MultinomialNB()),
 ])

In [85]:
text_clf.fit(twenty_train.data, twenty_train.target)

Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...inear_tf=False, use_idf=True)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [86]:
twenty_test = fetch_20newsgroups(subset='test',
     categories=categories, shuffle=True, random_state=42)
#print(twenty_test)

In [87]:
docs_test = twenty_test.data

In [88]:
predicted = text_clf.predict(docs_test)

In [89]:
np.mean(predicted == twenty_test.target)            


0.8348868175765646

In [90]:
from sklearn.linear_model import SGDClassifier

In [91]:
text_clf = Pipeline([('vect', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('clf', SGDClassifier(loss='hinge', penalty='l2',
                                            alpha=1e-3, random_state=42,
                                            max_iter=5, tol=None)),
 ])

In [92]:
text_clf.fit(twenty_train.data, twenty_train.target) 

Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...ty='l2', power_t=0.5, random_state=42, shuffle=True,
       tol=None, verbose=0, warm_start=False))])

In [93]:
predicted = text_clf.predict(docs_test)

In [94]:
np.mean(predicted == twenty_test.target)

0.9127829560585885

In [95]:
from sklearn import metrics

In [96]:
# I feel like it's kind of late to be importing metrics...

In [97]:
print(metrics.classification_report(twenty_test.target, predicted,
     target_names=twenty_test.target_names))

                        precision    recall  f1-score   support

           alt.atheism       0.95      0.81      0.87       319
         comp.graphics       0.88      0.97      0.92       389
               sci.med       0.94      0.90      0.92       396
soc.religion.christian       0.90      0.95      0.93       398

           avg / total       0.92      0.91      0.91      1502



In [98]:
metrics.confusion_matrix(twenty_test.target, predicted)

array([[258,  11,  15,  35],
       [  4, 379,   3,   3],
       [  5,  33, 355,   3],
       [  5,  10,   4, 379]], dtype=int64)

In [99]:
from sklearn.model_selection import GridSearchCV

In [100]:
parameters = {'vect__ngram_range': [(1, 1), (1, 2)],
               'tfidf__use_idf': (True, False),
               'clf__alpha': (1e-2, 1e-3),
 }

In [101]:
gs_clf = GridSearchCV(text_clf, parameters, n_jobs=-1)

In [102]:
gs_clf = gs_clf.fit(twenty_train.data[:400], twenty_train.target[:400])

In [103]:
twenty_train.target_names[gs_clf.predict(['Jesus works for HP'])[0]]

'soc.religion.christian'

In [104]:
gs_clf.best_score_  

0.9

In [105]:
for param_name in sorted(parameters.keys()):
     print("%s: %r" % (param_name, gs_clf.best_params_[param_name]))

clf__alpha: 0.001
tfidf__use_idf: True
vect__ngram_range: (1, 1)


In [106]:
# done with tutorials -- moving on to example

In [107]:
import sys

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import Perceptron
from sklearn.pipeline import Pipeline
from sklearn.datasets import load_files
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [108]:

# simple python script to collect text paragraphs from various languages on the
# same topic namely the Wikipedia encyclopedia itself

import os
try:
    # Python 2 compat
    from urllib2 import Request, build_opener
except ImportError:
    # Python 3
    from urllib.request import Request, build_opener

import lxml.html
from lxml.etree import ElementTree
import numpy as np

import codecs

pages = {
    u'ar': u'http://ar.wikipedia.org/wiki/%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7',
    u'de': u'http://de.wikipedia.org/wiki/Wikipedia',
    u'en': u'https://en.wikipedia.org/wiki/Wikipedia',
    u'es': u'http://es.wikipedia.org/wiki/Wikipedia',
    u'fr': u'http://fr.wikipedia.org/wiki/Wikip%C3%A9dia',
    u'it': u'http://it.wikipedia.org/wiki/Wikipedia',
    u'ja': u'http://ja.wikipedia.org/wiki/Wikipedia',
    u'nl': u'http://nl.wikipedia.org/wiki/Wikipedia',
    u'pl': u'http://pl.wikipedia.org/wiki/Wikipedia',
    u'pt': u'http://pt.wikipedia.org/wiki/Wikip%C3%A9dia',
    u'ru': u'http://ru.wikipedia.org/wiki/%D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F',
    u'zh': u'http://zh.wikipedia.org/wiki/Wikipedia',
}

html_folder = u'html'
text_folder = u'paragraphs'
short_text_folder = u'short_paragraphs'
n_words_per_short_text = 5


if not os.path.exists(html_folder):
    os.makedirs(html_folder)

for lang, page in pages.items():

    text_lang_folder = os.path.join(text_folder, lang)
    if not os.path.exists(text_lang_folder):
        os.makedirs(text_lang_folder)

    short_text_lang_folder = os.path.join(short_text_folder, lang)
    if not os.path.exists(short_text_lang_folder):
        os.makedirs(short_text_lang_folder)

    opener = build_opener()
    html_filename = os.path.join(html_folder, lang + '.html')
    if not os.path.exists(html_filename):
        print("Downloading %s" % page)
        request = Request(page)
        # change the User Agent to avoid being blocked by Wikipedia
        # downloading a couple of articles should not be considered abusive
        request.add_header('User-Agent', 'OpenAnything/1.0')
        html_content = opener.open(request).read()
        open(html_filename, 'wb').write(html_content)

    # decode the payload explicitly as UTF-8 since lxml is confused for some
    # reason
    with codecs.open(html_filename,'r','utf-8') as html_file:
        html_content = html_file.read()
    tree = ElementTree(lxml.html.document_fromstring(html_content))
    i = 0
    j = 0
    for p in tree.findall('//p'):
        content = p.text_content()
        if len(content) < 100:
            # skip paragraphs that are too short - probably too noisy and not
            # representative of the actual language
            continue

        text_filename = os.path.join(text_lang_folder,
                                     '%s_%04d.txt' % (lang, i))
        print("Writing %s" % text_filename)
        open(text_filename, 'wb').write(content.encode('utf-8', 'ignore'))
        i += 1

        # split the paragraph into fake smaller paragraphs to make the
        # problem harder e.g. more similar to tweets
        if lang in ('zh', 'ja'):
        # FIXME: whitespace tokenizing does not work on chinese and japanese
            continue
        words = content.split()
        n_groups = len(words) / n_words_per_short_text
        if n_groups < 1:
            continue
        groups = np.array_split(words, n_groups)

        for group in groups:
            small_content = u" ".join(group)

            short_text_filename = os.path.join(short_text_lang_folder,
                                               '%s_%04d.txt' % (lang, j))
            print("Writing %s" % short_text_filename)
            open(short_text_filename, 'wb').write(
                small_content.encode('utf-8', 'ignore'))
            j += 1
            if j >= 1000:
                break

import os

Writing paragraphs\ar\ar_0000.txt
Writing short_paragraphs\ar\ar_0000.txt
Writing short_paragraphs\ar\ar_0001.txt
Writing short_paragraphs\ar\ar_0002.txt
Writing short_paragraphs\ar\ar_0003.txt
Writing short_paragraphs\ar\ar_0004.txt
Writing short_paragraphs\ar\ar_0005.txt
Writing short_paragraphs\ar\ar_0006.txt
Writing short_paragraphs\ar\ar_0007.txt
Writing short_paragraphs\ar\ar_0008.txt
Writing short_paragraphs\ar\ar_0009.txt
Writing short_paragraphs\ar\ar_0010.txt
Writing paragraphs\ar\ar_0001.txt
Writing short_paragraphs\ar\ar_0011.txt
Writing short_paragraphs\ar\ar_0012.txt
Writing short_paragraphs\ar\ar_0013.txt
Writing short_paragraphs\ar\ar_0014.txt
Writing short_paragraphs\ar\ar_0015.txt
Writing short_paragraphs\ar\ar_0016.txt
Writing short_paragraphs\ar\ar_0017.txt
Writing short_paragraphs\ar\ar_0018.txt
Writing short_paragraphs\ar\ar_0019.txt
Writing short_paragraphs\ar\ar_0020.txt
Writing short_paragraphs\ar\ar_0021.txt
Writing short_paragraphs\ar\ar_0022.txt
Writing shor

Writing short_paragraphs\ar\ar_0195.txt
Writing short_paragraphs\ar\ar_0196.txt
Writing short_paragraphs\ar\ar_0197.txt
Writing short_paragraphs\ar\ar_0198.txt
Writing paragraphs\ar\ar_0019.txt
Writing short_paragraphs\ar\ar_0199.txt
Writing short_paragraphs\ar\ar_0200.txt
Writing short_paragraphs\ar\ar_0201.txt
Writing short_paragraphs\ar\ar_0202.txt
Writing short_paragraphs\ar\ar_0203.txt
Writing short_paragraphs\ar\ar_0204.txt
Writing short_paragraphs\ar\ar_0205.txt
Writing short_paragraphs\ar\ar_0206.txt
Writing paragraphs\ar\ar_0020.txt
Writing short_paragraphs\ar\ar_0207.txt
Writing short_paragraphs\ar\ar_0208.txt
Writing short_paragraphs\ar\ar_0209.txt
Writing short_paragraphs\ar\ar_0210.txt
Writing short_paragraphs\ar\ar_0211.txt
Writing short_paragraphs\ar\ar_0212.txt
Writing short_paragraphs\ar\ar_0213.txt
Writing short_paragraphs\ar\ar_0214.txt
Writing short_paragraphs\ar\ar_0215.txt
Writing paragraphs\ar\ar_0021.txt
Writing short_paragraphs\ar\ar_0216.txt
Writing short_para

Writing short_paragraphs\de\de_0093.txt
Writing short_paragraphs\de\de_0094.txt
Writing short_paragraphs\de\de_0095.txt
Writing short_paragraphs\de\de_0096.txt
Writing short_paragraphs\de\de_0097.txt
Writing short_paragraphs\de\de_0098.txt
Writing short_paragraphs\de\de_0099.txt
Writing short_paragraphs\de\de_0100.txt
Writing short_paragraphs\de\de_0101.txt
Writing short_paragraphs\de\de_0102.txt
Writing short_paragraphs\de\de_0103.txt
Writing short_paragraphs\de\de_0104.txt
Writing paragraphs\de\de_0008.txt
Writing short_paragraphs\de\de_0105.txt
Writing short_paragraphs\de\de_0106.txt
Writing short_paragraphs\de\de_0107.txt
Writing short_paragraphs\de\de_0108.txt
Writing short_paragraphs\de\de_0109.txt
Writing short_paragraphs\de\de_0110.txt
Writing short_paragraphs\de\de_0111.txt
Writing short_paragraphs\de\de_0112.txt
Writing short_paragraphs\de\de_0113.txt
Writing short_paragraphs\de\de_0114.txt
Writing short_paragraphs\de\de_0115.txt
Writing short_paragraphs\de\de_0116.txt
Writin

Writing short_paragraphs\de\de_0293.txt
Writing short_paragraphs\de\de_0294.txt
Writing short_paragraphs\de\de_0295.txt
Writing short_paragraphs\de\de_0296.txt
Writing short_paragraphs\de\de_0297.txt
Writing short_paragraphs\de\de_0298.txt
Writing short_paragraphs\de\de_0299.txt
Writing paragraphs\de\de_0022.txt
Writing short_paragraphs\de\de_0300.txt
Writing short_paragraphs\de\de_0301.txt
Writing short_paragraphs\de\de_0302.txt
Writing short_paragraphs\de\de_0303.txt
Writing short_paragraphs\de\de_0304.txt
Writing short_paragraphs\de\de_0305.txt
Writing short_paragraphs\de\de_0306.txt
Writing short_paragraphs\de\de_0307.txt
Writing short_paragraphs\de\de_0308.txt
Writing short_paragraphs\de\de_0309.txt
Writing short_paragraphs\de\de_0310.txt
Writing short_paragraphs\de\de_0311.txt
Writing short_paragraphs\de\de_0312.txt
Writing short_paragraphs\de\de_0313.txt
Writing short_paragraphs\de\de_0314.txt
Writing short_paragraphs\de\de_0315.txt
Writing short_paragraphs\de\de_0316.txt
Writin

Writing short_paragraphs\de\de_0488.txt
Writing short_paragraphs\de\de_0489.txt
Writing short_paragraphs\de\de_0490.txt
Writing short_paragraphs\de\de_0491.txt
Writing short_paragraphs\de\de_0492.txt
Writing short_paragraphs\de\de_0493.txt
Writing paragraphs\de\de_0037.txt
Writing short_paragraphs\de\de_0494.txt
Writing short_paragraphs\de\de_0495.txt
Writing short_paragraphs\de\de_0496.txt
Writing short_paragraphs\de\de_0497.txt
Writing short_paragraphs\de\de_0498.txt
Writing short_paragraphs\de\de_0499.txt
Writing short_paragraphs\de\de_0500.txt
Writing short_paragraphs\de\de_0501.txt
Writing paragraphs\de\de_0038.txt
Writing short_paragraphs\de\de_0502.txt
Writing short_paragraphs\de\de_0503.txt
Writing short_paragraphs\de\de_0504.txt
Writing short_paragraphs\de\de_0505.txt
Writing short_paragraphs\de\de_0506.txt
Writing short_paragraphs\de\de_0507.txt
Writing short_paragraphs\de\de_0508.txt
Writing paragraphs\de\de_0039.txt
Writing short_paragraphs\de\de_0509.txt
Writing short_para

Writing short_paragraphs\de\de_0686.txt
Writing paragraphs\de\de_0053.txt
Writing short_paragraphs\de\de_0687.txt
Writing short_paragraphs\de\de_0688.txt
Writing short_paragraphs\de\de_0689.txt
Writing short_paragraphs\de\de_0690.txt
Writing short_paragraphs\de\de_0691.txt
Writing short_paragraphs\de\de_0692.txt
Writing short_paragraphs\de\de_0693.txt
Writing short_paragraphs\de\de_0694.txt
Writing short_paragraphs\de\de_0695.txt
Writing short_paragraphs\de\de_0696.txt
Writing short_paragraphs\de\de_0697.txt
Writing short_paragraphs\de\de_0698.txt
Writing short_paragraphs\de\de_0699.txt
Writing paragraphs\de\de_0054.txt
Writing short_paragraphs\de\de_0700.txt
Writing short_paragraphs\de\de_0701.txt
Writing short_paragraphs\de\de_0702.txt
Writing short_paragraphs\de\de_0703.txt
Writing short_paragraphs\de\de_0704.txt
Writing short_paragraphs\de\de_0705.txt
Writing short_paragraphs\de\de_0706.txt
Writing short_paragraphs\de\de_0707.txt
Writing short_paragraphs\de\de_0708.txt
Writing shor

Writing short_paragraphs\de\de_0878.txt
Writing short_paragraphs\de\de_0879.txt
Writing short_paragraphs\de\de_0880.txt
Writing short_paragraphs\de\de_0881.txt
Writing short_paragraphs\de\de_0882.txt
Writing short_paragraphs\de\de_0883.txt
Writing short_paragraphs\de\de_0884.txt
Writing short_paragraphs\de\de_0885.txt
Writing short_paragraphs\de\de_0886.txt
Writing short_paragraphs\de\de_0887.txt
Writing short_paragraphs\de\de_0888.txt
Writing short_paragraphs\de\de_0889.txt
Writing short_paragraphs\de\de_0890.txt
Writing short_paragraphs\de\de_0891.txt
Writing short_paragraphs\de\de_0892.txt
Writing short_paragraphs\de\de_0893.txt
Writing short_paragraphs\de\de_0894.txt
Writing paragraphs\de\de_0070.txt
Writing short_paragraphs\de\de_0895.txt
Writing short_paragraphs\de\de_0896.txt
Writing short_paragraphs\de\de_0897.txt
Writing short_paragraphs\de\de_0898.txt
Writing short_paragraphs\de\de_0899.txt
Writing short_paragraphs\de\de_0900.txt
Writing short_paragraphs\de\de_0901.txt
Writin

Writing short_paragraphs\de\de_1044.txt
Writing paragraphs\de\de_0122.txt
Writing short_paragraphs\de\de_1045.txt
Writing paragraphs\de\de_0123.txt
Writing short_paragraphs\de\de_1046.txt
Writing paragraphs\de\de_0124.txt
Writing short_paragraphs\de\de_1047.txt
Writing paragraphs\de\de_0125.txt
Writing short_paragraphs\de\de_1048.txt
Writing paragraphs\de\de_0126.txt
Writing short_paragraphs\de\de_1049.txt
Writing paragraphs\de\de_0127.txt
Writing short_paragraphs\de\de_1050.txt
Writing paragraphs\de\de_0128.txt
Writing short_paragraphs\de\de_1051.txt
Writing paragraphs\de\de_0129.txt
Writing short_paragraphs\de\de_1052.txt
Writing paragraphs\de\de_0130.txt
Writing short_paragraphs\de\de_1053.txt
Writing paragraphs\de\de_0131.txt
Writing short_paragraphs\de\de_1054.txt
Writing paragraphs\de\de_0132.txt
Writing short_paragraphs\de\de_1055.txt
Writing paragraphs\de\de_0133.txt
Writing short_paragraphs\de\de_1056.txt
Writing paragraphs\de\de_0134.txt
Writing short_paragraphs\de\de_1057.tx

Writing short_paragraphs\en\en_0144.txt
Writing short_paragraphs\en\en_0145.txt
Writing short_paragraphs\en\en_0146.txt
Writing paragraphs\en\en_0009.txt
Writing short_paragraphs\en\en_0147.txt
Writing short_paragraphs\en\en_0148.txt
Writing short_paragraphs\en\en_0149.txt
Writing short_paragraphs\en\en_0150.txt
Writing short_paragraphs\en\en_0151.txt
Writing short_paragraphs\en\en_0152.txt
Writing short_paragraphs\en\en_0153.txt
Writing short_paragraphs\en\en_0154.txt
Writing short_paragraphs\en\en_0155.txt
Writing short_paragraphs\en\en_0156.txt
Writing short_paragraphs\en\en_0157.txt
Writing short_paragraphs\en\en_0158.txt
Writing short_paragraphs\en\en_0159.txt
Writing short_paragraphs\en\en_0160.txt
Writing short_paragraphs\en\en_0161.txt
Writing short_paragraphs\en\en_0162.txt
Writing short_paragraphs\en\en_0163.txt
Writing short_paragraphs\en\en_0164.txt
Writing short_paragraphs\en\en_0165.txt
Writing short_paragraphs\en\en_0166.txt
Writing short_paragraphs\en\en_0167.txt
Writin

Writing short_paragraphs\en\en_0340.txt
Writing short_paragraphs\en\en_0341.txt
Writing short_paragraphs\en\en_0342.txt
Writing short_paragraphs\en\en_0343.txt
Writing short_paragraphs\en\en_0344.txt
Writing short_paragraphs\en\en_0345.txt
Writing short_paragraphs\en\en_0346.txt
Writing short_paragraphs\en\en_0347.txt
Writing short_paragraphs\en\en_0348.txt
Writing short_paragraphs\en\en_0349.txt
Writing short_paragraphs\en\en_0350.txt
Writing short_paragraphs\en\en_0351.txt
Writing short_paragraphs\en\en_0352.txt
Writing short_paragraphs\en\en_0353.txt
Writing short_paragraphs\en\en_0354.txt
Writing short_paragraphs\en\en_0355.txt
Writing paragraphs\en\en_0020.txt
Writing short_paragraphs\en\en_0356.txt
Writing short_paragraphs\en\en_0357.txt
Writing short_paragraphs\en\en_0358.txt
Writing short_paragraphs\en\en_0359.txt
Writing short_paragraphs\en\en_0360.txt
Writing short_paragraphs\en\en_0361.txt
Writing paragraphs\en\en_0021.txt
Writing short_paragraphs\en\en_0362.txt
Writing shor

Writing paragraphs\en\en_0031.txt
Writing short_paragraphs\en\en_0542.txt
Writing short_paragraphs\en\en_0543.txt
Writing short_paragraphs\en\en_0544.txt
Writing short_paragraphs\en\en_0545.txt
Writing short_paragraphs\en\en_0546.txt
Writing short_paragraphs\en\en_0547.txt
Writing short_paragraphs\en\en_0548.txt
Writing paragraphs\en\en_0032.txt
Writing short_paragraphs\en\en_0549.txt
Writing short_paragraphs\en\en_0550.txt
Writing short_paragraphs\en\en_0551.txt
Writing short_paragraphs\en\en_0552.txt
Writing short_paragraphs\en\en_0553.txt
Writing short_paragraphs\en\en_0554.txt
Writing short_paragraphs\en\en_0555.txt
Writing short_paragraphs\en\en_0556.txt
Writing short_paragraphs\en\en_0557.txt
Writing short_paragraphs\en\en_0558.txt
Writing short_paragraphs\en\en_0559.txt
Writing short_paragraphs\en\en_0560.txt
Writing short_paragraphs\en\en_0561.txt
Writing short_paragraphs\en\en_0562.txt
Writing short_paragraphs\en\en_0563.txt
Writing short_paragraphs\en\en_0564.txt
Writing shor

Writing short_paragraphs\en\en_0745.txt
Writing short_paragraphs\en\en_0746.txt
Writing short_paragraphs\en\en_0747.txt
Writing short_paragraphs\en\en_0748.txt
Writing paragraphs\en\en_0043.txt
Writing short_paragraphs\en\en_0749.txt
Writing short_paragraphs\en\en_0750.txt
Writing short_paragraphs\en\en_0751.txt
Writing short_paragraphs\en\en_0752.txt
Writing short_paragraphs\en\en_0753.txt
Writing short_paragraphs\en\en_0754.txt
Writing short_paragraphs\en\en_0755.txt
Writing short_paragraphs\en\en_0756.txt
Writing short_paragraphs\en\en_0757.txt
Writing short_paragraphs\en\en_0758.txt
Writing short_paragraphs\en\en_0759.txt
Writing short_paragraphs\en\en_0760.txt
Writing short_paragraphs\en\en_0761.txt
Writing paragraphs\en\en_0044.txt
Writing short_paragraphs\en\en_0762.txt
Writing short_paragraphs\en\en_0763.txt
Writing short_paragraphs\en\en_0764.txt
Writing short_paragraphs\en\en_0765.txt
Writing short_paragraphs\en\en_0766.txt
Writing short_paragraphs\en\en_0767.txt
Writing shor

Writing short_paragraphs\en\en_0944.txt
Writing short_paragraphs\en\en_0945.txt
Writing short_paragraphs\en\en_0946.txt
Writing short_paragraphs\en\en_0947.txt
Writing short_paragraphs\en\en_0948.txt
Writing short_paragraphs\en\en_0949.txt
Writing short_paragraphs\en\en_0950.txt
Writing short_paragraphs\en\en_0951.txt
Writing short_paragraphs\en\en_0952.txt
Writing short_paragraphs\en\en_0953.txt
Writing short_paragraphs\en\en_0954.txt
Writing short_paragraphs\en\en_0955.txt
Writing short_paragraphs\en\en_0956.txt
Writing short_paragraphs\en\en_0957.txt
Writing short_paragraphs\en\en_0958.txt
Writing short_paragraphs\en\en_0959.txt
Writing short_paragraphs\en\en_0960.txt
Writing short_paragraphs\en\en_0961.txt
Writing short_paragraphs\en\en_0962.txt
Writing short_paragraphs\en\en_0963.txt
Writing short_paragraphs\en\en_0964.txt
Writing short_paragraphs\en\en_0965.txt
Writing short_paragraphs\en\en_0966.txt
Writing short_paragraphs\en\en_0967.txt
Writing short_paragraphs\en\en_0968.txt


Writing paragraphs\en\en_0138.txt
Writing short_paragraphs\en\en_1081.txt
Writing paragraphs\en\en_0139.txt
Writing short_paragraphs\en\en_1082.txt
Writing paragraphs\en\en_0140.txt
Writing short_paragraphs\en\en_1083.txt
Writing paragraphs\en\en_0141.txt
Writing short_paragraphs\en\en_1084.txt
Writing paragraphs\en\en_0142.txt
Writing short_paragraphs\en\en_1085.txt
Writing paragraphs\en\en_0143.txt
Writing short_paragraphs\en\en_1086.txt
Writing paragraphs\en\en_0144.txt
Writing short_paragraphs\en\en_1087.txt
Writing paragraphs\en\en_0145.txt
Writing short_paragraphs\en\en_1088.txt
Writing paragraphs\en\en_0146.txt
Writing short_paragraphs\en\en_1089.txt
Writing paragraphs\en\en_0147.txt
Writing short_paragraphs\en\en_1090.txt
Writing paragraphs\es\es_0000.txt
Writing short_paragraphs\es\es_0000.txt
Writing short_paragraphs\es\es_0001.txt
Writing short_paragraphs\es\es_0002.txt
Writing short_paragraphs\es\es_0003.txt
Writing short_paragraphs\es\es_0004.txt
Writing short_paragraphs\e

Writing short_paragraphs\es\es_0181.txt
Writing short_paragraphs\es\es_0182.txt
Writing short_paragraphs\es\es_0183.txt
Writing short_paragraphs\es\es_0184.txt
Writing short_paragraphs\es\es_0185.txt
Writing short_paragraphs\es\es_0186.txt
Writing short_paragraphs\es\es_0187.txt
Writing short_paragraphs\es\es_0188.txt
Writing short_paragraphs\es\es_0189.txt
Writing short_paragraphs\es\es_0190.txt
Writing short_paragraphs\es\es_0191.txt
Writing paragraphs\es\es_0016.txt
Writing short_paragraphs\es\es_0192.txt
Writing short_paragraphs\es\es_0193.txt
Writing short_paragraphs\es\es_0194.txt
Writing short_paragraphs\es\es_0195.txt
Writing short_paragraphs\es\es_0196.txt
Writing short_paragraphs\es\es_0197.txt
Writing short_paragraphs\es\es_0198.txt
Writing short_paragraphs\es\es_0199.txt
Writing short_paragraphs\es\es_0200.txt
Writing short_paragraphs\es\es_0201.txt
Writing short_paragraphs\es\es_0202.txt
Writing short_paragraphs\es\es_0203.txt
Writing short_paragraphs\es\es_0204.txt
Writin

Writing short_paragraphs\es\es_0375.txt
Writing short_paragraphs\es\es_0376.txt
Writing short_paragraphs\es\es_0377.txt
Writing short_paragraphs\es\es_0378.txt
Writing short_paragraphs\es\es_0379.txt
Writing short_paragraphs\es\es_0380.txt
Writing short_paragraphs\es\es_0381.txt
Writing short_paragraphs\es\es_0382.txt
Writing short_paragraphs\es\es_0383.txt
Writing short_paragraphs\es\es_0384.txt
Writing short_paragraphs\es\es_0385.txt
Writing short_paragraphs\es\es_0386.txt
Writing short_paragraphs\es\es_0387.txt
Writing short_paragraphs\es\es_0388.txt
Writing short_paragraphs\es\es_0389.txt
Writing short_paragraphs\es\es_0390.txt
Writing short_paragraphs\es\es_0391.txt
Writing short_paragraphs\es\es_0392.txt
Writing paragraphs\es\es_0029.txt
Writing short_paragraphs\es\es_0393.txt
Writing short_paragraphs\es\es_0394.txt
Writing short_paragraphs\es\es_0395.txt
Writing short_paragraphs\es\es_0396.txt
Writing short_paragraphs\es\es_0397.txt
Writing short_paragraphs\es\es_0398.txt
Writin

Writing short_paragraphs\es\es_0578.txt
Writing short_paragraphs\es\es_0579.txt
Writing short_paragraphs\es\es_0580.txt
Writing short_paragraphs\es\es_0581.txt
Writing short_paragraphs\es\es_0582.txt
Writing short_paragraphs\es\es_0583.txt
Writing short_paragraphs\es\es_0584.txt
Writing paragraphs\es\es_0040.txt
Writing short_paragraphs\es\es_0585.txt
Writing short_paragraphs\es\es_0586.txt
Writing short_paragraphs\es\es_0587.txt
Writing short_paragraphs\es\es_0588.txt
Writing short_paragraphs\es\es_0589.txt
Writing short_paragraphs\es\es_0590.txt
Writing short_paragraphs\es\es_0591.txt
Writing short_paragraphs\es\es_0592.txt
Writing short_paragraphs\es\es_0593.txt
Writing short_paragraphs\es\es_0594.txt
Writing short_paragraphs\es\es_0595.txt
Writing short_paragraphs\es\es_0596.txt
Writing short_paragraphs\es\es_0597.txt
Writing short_paragraphs\es\es_0598.txt
Writing paragraphs\es\es_0041.txt
Writing short_paragraphs\es\es_0599.txt
Writing short_paragraphs\es\es_0600.txt
Writing shor

Writing short_paragraphs\es\es_0776.txt
Writing short_paragraphs\es\es_0777.txt
Writing short_paragraphs\es\es_0778.txt
Writing short_paragraphs\es\es_0779.txt
Writing short_paragraphs\es\es_0780.txt
Writing short_paragraphs\es\es_0781.txt
Writing short_paragraphs\es\es_0782.txt
Writing short_paragraphs\es\es_0783.txt
Writing short_paragraphs\es\es_0784.txt
Writing short_paragraphs\es\es_0785.txt
Writing short_paragraphs\es\es_0786.txt
Writing short_paragraphs\es\es_0787.txt
Writing short_paragraphs\es\es_0788.txt
Writing paragraphs\es\es_0053.txt
Writing short_paragraphs\es\es_0789.txt
Writing short_paragraphs\es\es_0790.txt
Writing short_paragraphs\es\es_0791.txt
Writing short_paragraphs\es\es_0792.txt
Writing short_paragraphs\es\es_0793.txt
Writing short_paragraphs\es\es_0794.txt
Writing paragraphs\es\es_0054.txt
Writing short_paragraphs\es\es_0795.txt
Writing short_paragraphs\es\es_0796.txt
Writing short_paragraphs\es\es_0797.txt
Writing short_paragraphs\es\es_0798.txt
Writing shor

Writing short_paragraphs\es\es_0978.txt
Writing short_paragraphs\es\es_0979.txt
Writing short_paragraphs\es\es_0980.txt
Writing short_paragraphs\es\es_0981.txt
Writing short_paragraphs\es\es_0982.txt
Writing short_paragraphs\es\es_0983.txt
Writing short_paragraphs\es\es_0984.txt
Writing short_paragraphs\es\es_0985.txt
Writing short_paragraphs\es\es_0986.txt
Writing short_paragraphs\es\es_0987.txt
Writing short_paragraphs\es\es_0988.txt
Writing short_paragraphs\es\es_0989.txt
Writing paragraphs\es\es_0065.txt
Writing short_paragraphs\es\es_0990.txt
Writing short_paragraphs\es\es_0991.txt
Writing short_paragraphs\es\es_0992.txt
Writing short_paragraphs\es\es_0993.txt
Writing short_paragraphs\es\es_0994.txt
Writing paragraphs\es\es_0066.txt
Writing short_paragraphs\es\es_0995.txt
Writing short_paragraphs\es\es_0996.txt
Writing short_paragraphs\es\es_0997.txt
Writing short_paragraphs\es\es_0998.txt
Writing short_paragraphs\es\es_0999.txt
Writing paragraphs\es\es_0067.txt
Writing short_para

Writing short_paragraphs\fr\fr_0083.txt
Writing short_paragraphs\fr\fr_0084.txt
Writing short_paragraphs\fr\fr_0085.txt
Writing short_paragraphs\fr\fr_0086.txt
Writing short_paragraphs\fr\fr_0087.txt
Writing paragraphs\fr\fr_0005.txt
Writing short_paragraphs\fr\fr_0088.txt
Writing short_paragraphs\fr\fr_0089.txt
Writing short_paragraphs\fr\fr_0090.txt
Writing short_paragraphs\fr\fr_0091.txt
Writing short_paragraphs\fr\fr_0092.txt
Writing short_paragraphs\fr\fr_0093.txt
Writing short_paragraphs\fr\fr_0094.txt
Writing short_paragraphs\fr\fr_0095.txt
Writing short_paragraphs\fr\fr_0096.txt
Writing short_paragraphs\fr\fr_0097.txt
Writing short_paragraphs\fr\fr_0098.txt
Writing short_paragraphs\fr\fr_0099.txt
Writing short_paragraphs\fr\fr_0100.txt
Writing short_paragraphs\fr\fr_0101.txt
Writing short_paragraphs\fr\fr_0102.txt
Writing short_paragraphs\fr\fr_0103.txt
Writing short_paragraphs\fr\fr_0104.txt
Writing short_paragraphs\fr\fr_0105.txt
Writing short_paragraphs\fr\fr_0106.txt
Writin

Writing paragraphs\fr\fr_0018.txt
Writing short_paragraphs\fr\fr_0285.txt
Writing short_paragraphs\fr\fr_0286.txt
Writing short_paragraphs\fr\fr_0287.txt
Writing short_paragraphs\fr\fr_0288.txt
Writing short_paragraphs\fr\fr_0289.txt
Writing short_paragraphs\fr\fr_0290.txt
Writing short_paragraphs\fr\fr_0291.txt
Writing short_paragraphs\fr\fr_0292.txt
Writing short_paragraphs\fr\fr_0293.txt
Writing short_paragraphs\fr\fr_0294.txt
Writing short_paragraphs\fr\fr_0295.txt
Writing short_paragraphs\fr\fr_0296.txt
Writing short_paragraphs\fr\fr_0297.txt
Writing short_paragraphs\fr\fr_0298.txt
Writing short_paragraphs\fr\fr_0299.txt
Writing short_paragraphs\fr\fr_0300.txt
Writing paragraphs\fr\fr_0019.txt
Writing short_paragraphs\fr\fr_0301.txt
Writing short_paragraphs\fr\fr_0302.txt
Writing short_paragraphs\fr\fr_0303.txt
Writing short_paragraphs\fr\fr_0304.txt
Writing paragraphs\fr\fr_0020.txt
Writing short_paragraphs\fr\fr_0305.txt
Writing short_paragraphs\fr\fr_0306.txt
Writing short_para

Writing short_paragraphs\fr\fr_0481.txt
Writing short_paragraphs\fr\fr_0482.txt
Writing short_paragraphs\fr\fr_0483.txt
Writing short_paragraphs\fr\fr_0484.txt
Writing short_paragraphs\fr\fr_0485.txt
Writing short_paragraphs\fr\fr_0486.txt
Writing short_paragraphs\fr\fr_0487.txt
Writing short_paragraphs\fr\fr_0488.txt
Writing short_paragraphs\fr\fr_0489.txt
Writing short_paragraphs\fr\fr_0490.txt
Writing short_paragraphs\fr\fr_0491.txt
Writing short_paragraphs\fr\fr_0492.txt
Writing short_paragraphs\fr\fr_0493.txt
Writing short_paragraphs\fr\fr_0494.txt
Writing short_paragraphs\fr\fr_0495.txt
Writing short_paragraphs\fr\fr_0496.txt
Writing short_paragraphs\fr\fr_0497.txt
Writing short_paragraphs\fr\fr_0498.txt
Writing short_paragraphs\fr\fr_0499.txt
Writing short_paragraphs\fr\fr_0500.txt
Writing short_paragraphs\fr\fr_0501.txt
Writing paragraphs\fr\fr_0031.txt
Writing short_paragraphs\fr\fr_0502.txt
Writing short_paragraphs\fr\fr_0503.txt
Writing short_paragraphs\fr\fr_0504.txt
Writin

Writing short_paragraphs\fr\fr_0679.txt
Writing short_paragraphs\fr\fr_0680.txt
Writing short_paragraphs\fr\fr_0681.txt
Writing short_paragraphs\fr\fr_0682.txt
Writing short_paragraphs\fr\fr_0683.txt
Writing short_paragraphs\fr\fr_0684.txt
Writing short_paragraphs\fr\fr_0685.txt
Writing short_paragraphs\fr\fr_0686.txt
Writing short_paragraphs\fr\fr_0687.txt
Writing short_paragraphs\fr\fr_0688.txt
Writing paragraphs\fr\fr_0048.txt
Writing short_paragraphs\fr\fr_0689.txt
Writing short_paragraphs\fr\fr_0690.txt
Writing short_paragraphs\fr\fr_0691.txt
Writing short_paragraphs\fr\fr_0692.txt
Writing short_paragraphs\fr\fr_0693.txt
Writing short_paragraphs\fr\fr_0694.txt
Writing short_paragraphs\fr\fr_0695.txt
Writing short_paragraphs\fr\fr_0696.txt
Writing short_paragraphs\fr\fr_0697.txt
Writing paragraphs\fr\fr_0049.txt
Writing short_paragraphs\fr\fr_0698.txt
Writing short_paragraphs\fr\fr_0699.txt
Writing short_paragraphs\fr\fr_0700.txt
Writing short_paragraphs\fr\fr_0701.txt
Writing para

Writing short_paragraphs\fr\fr_0878.txt
Writing short_paragraphs\fr\fr_0879.txt
Writing short_paragraphs\fr\fr_0880.txt
Writing short_paragraphs\fr\fr_0881.txt
Writing short_paragraphs\fr\fr_0882.txt
Writing short_paragraphs\fr\fr_0883.txt
Writing short_paragraphs\fr\fr_0884.txt
Writing short_paragraphs\fr\fr_0885.txt
Writing short_paragraphs\fr\fr_0886.txt
Writing short_paragraphs\fr\fr_0887.txt
Writing short_paragraphs\fr\fr_0888.txt
Writing short_paragraphs\fr\fr_0889.txt
Writing short_paragraphs\fr\fr_0890.txt
Writing short_paragraphs\fr\fr_0891.txt
Writing short_paragraphs\fr\fr_0892.txt
Writing short_paragraphs\fr\fr_0893.txt
Writing short_paragraphs\fr\fr_0894.txt
Writing short_paragraphs\fr\fr_0895.txt
Writing short_paragraphs\fr\fr_0896.txt
Writing short_paragraphs\fr\fr_0897.txt
Writing short_paragraphs\fr\fr_0898.txt
Writing paragraphs\fr\fr_0064.txt
Writing short_paragraphs\fr\fr_0899.txt
Writing short_paragraphs\fr\fr_0900.txt
Writing short_paragraphs\fr\fr_0901.txt
Writin

Writing paragraphs\fr\fr_0118.txt
Writing short_paragraphs\fr\fr_1043.txt
Writing paragraphs\fr\fr_0119.txt
Writing short_paragraphs\fr\fr_1044.txt
Writing paragraphs\fr\fr_0120.txt
Writing short_paragraphs\fr\fr_1045.txt
Writing paragraphs\fr\fr_0121.txt
Writing short_paragraphs\fr\fr_1046.txt
Writing paragraphs\fr\fr_0122.txt
Writing short_paragraphs\fr\fr_1047.txt
Writing paragraphs\fr\fr_0123.txt
Writing short_paragraphs\fr\fr_1048.txt
Writing paragraphs\fr\fr_0124.txt
Writing short_paragraphs\fr\fr_1049.txt
Writing paragraphs\fr\fr_0125.txt
Writing short_paragraphs\fr\fr_1050.txt
Writing paragraphs\it\it_0000.txt
Writing short_paragraphs\it\it_0000.txt
Writing short_paragraphs\it\it_0001.txt
Writing short_paragraphs\it\it_0002.txt
Writing short_paragraphs\it\it_0003.txt
Writing short_paragraphs\it\it_0004.txt
Writing short_paragraphs\it\it_0005.txt
Writing paragraphs\it\it_0001.txt
Writing short_paragraphs\it\it_0006.txt
Writing short_paragraphs\it\it_0007.txt
Writing short_paragr

Writing short_paragraphs\it\it_0178.txt
Writing short_paragraphs\it\it_0179.txt
Writing short_paragraphs\it\it_0180.txt
Writing short_paragraphs\it\it_0181.txt
Writing short_paragraphs\it\it_0182.txt
Writing short_paragraphs\it\it_0183.txt
Writing short_paragraphs\it\it_0184.txt
Writing short_paragraphs\it\it_0185.txt
Writing short_paragraphs\it\it_0186.txt
Writing short_paragraphs\it\it_0187.txt
Writing short_paragraphs\it\it_0188.txt
Writing short_paragraphs\it\it_0189.txt
Writing short_paragraphs\it\it_0190.txt
Writing short_paragraphs\it\it_0191.txt
Writing paragraphs\it\it_0015.txt
Writing short_paragraphs\it\it_0192.txt
Writing short_paragraphs\it\it_0193.txt
Writing short_paragraphs\it\it_0194.txt
Writing short_paragraphs\it\it_0195.txt
Writing short_paragraphs\it\it_0196.txt
Writing short_paragraphs\it\it_0197.txt
Writing short_paragraphs\it\it_0198.txt
Writing short_paragraphs\it\it_0199.txt
Writing short_paragraphs\it\it_0200.txt
Writing short_paragraphs\it\it_0201.txt
Writin

Writing short_paragraphs\it\it_0377.txt
Writing short_paragraphs\it\it_0378.txt
Writing short_paragraphs\it\it_0379.txt
Writing short_paragraphs\it\it_0380.txt
Writing short_paragraphs\it\it_0381.txt
Writing short_paragraphs\it\it_0382.txt
Writing short_paragraphs\it\it_0383.txt
Writing short_paragraphs\it\it_0384.txt
Writing short_paragraphs\it\it_0385.txt
Writing short_paragraphs\it\it_0386.txt
Writing short_paragraphs\it\it_0387.txt
Writing short_paragraphs\it\it_0388.txt
Writing short_paragraphs\it\it_0389.txt
Writing short_paragraphs\it\it_0390.txt
Writing short_paragraphs\it\it_0391.txt
Writing short_paragraphs\it\it_0392.txt
Writing short_paragraphs\it\it_0393.txt
Writing short_paragraphs\it\it_0394.txt
Writing short_paragraphs\it\it_0395.txt
Writing short_paragraphs\it\it_0396.txt
Writing short_paragraphs\it\it_0397.txt
Writing paragraphs\it\it_0025.txt
Writing short_paragraphs\it\it_0398.txt
Writing short_paragraphs\it\it_0399.txt
Writing short_paragraphs\it\it_0400.txt
Writin

Writing short_paragraphs\it\it_0575.txt
Writing short_paragraphs\it\it_0576.txt
Writing short_paragraphs\it\it_0577.txt
Writing paragraphs\it\it_0038.txt
Writing short_paragraphs\it\it_0578.txt
Writing short_paragraphs\it\it_0579.txt
Writing short_paragraphs\it\it_0580.txt
Writing short_paragraphs\it\it_0581.txt
Writing short_paragraphs\it\it_0582.txt
Writing short_paragraphs\it\it_0583.txt
Writing short_paragraphs\it\it_0584.txt
Writing short_paragraphs\it\it_0585.txt
Writing short_paragraphs\it\it_0586.txt
Writing short_paragraphs\it\it_0587.txt
Writing short_paragraphs\it\it_0588.txt
Writing short_paragraphs\it\it_0589.txt
Writing paragraphs\it\it_0039.txt
Writing short_paragraphs\it\it_0590.txt
Writing short_paragraphs\it\it_0591.txt
Writing short_paragraphs\it\it_0592.txt
Writing short_paragraphs\it\it_0593.txt
Writing short_paragraphs\it\it_0594.txt
Writing short_paragraphs\it\it_0595.txt
Writing short_paragraphs\it\it_0596.txt
Writing short_paragraphs\it\it_0597.txt
Writing shor

Writing short_paragraphs\it\it_0775.txt
Writing paragraphs\it\it_0048.txt
Writing short_paragraphs\it\it_0776.txt
Writing short_paragraphs\it\it_0777.txt
Writing short_paragraphs\it\it_0778.txt
Writing short_paragraphs\it\it_0779.txt
Writing short_paragraphs\it\it_0780.txt
Writing short_paragraphs\it\it_0781.txt
Writing short_paragraphs\it\it_0782.txt
Writing short_paragraphs\it\it_0783.txt
Writing paragraphs\it\it_0049.txt
Writing short_paragraphs\it\it_0784.txt
Writing short_paragraphs\it\it_0785.txt
Writing short_paragraphs\it\it_0786.txt
Writing short_paragraphs\it\it_0787.txt
Writing short_paragraphs\it\it_0788.txt
Writing short_paragraphs\it\it_0789.txt
Writing short_paragraphs\it\it_0790.txt
Writing short_paragraphs\it\it_0791.txt
Writing short_paragraphs\it\it_0792.txt
Writing short_paragraphs\it\it_0793.txt
Writing short_paragraphs\it\it_0794.txt
Writing short_paragraphs\it\it_0795.txt
Writing short_paragraphs\it\it_0796.txt
Writing short_paragraphs\it\it_0797.txt
Writing shor

Writing short_paragraphs\it\it_0974.txt
Writing short_paragraphs\it\it_0975.txt
Writing short_paragraphs\it\it_0976.txt
Writing short_paragraphs\it\it_0977.txt
Writing short_paragraphs\it\it_0978.txt
Writing short_paragraphs\it\it_0979.txt
Writing paragraphs\it\it_0061.txt
Writing short_paragraphs\it\it_0980.txt
Writing short_paragraphs\it\it_0981.txt
Writing short_paragraphs\it\it_0982.txt
Writing short_paragraphs\it\it_0983.txt
Writing short_paragraphs\it\it_0984.txt
Writing short_paragraphs\it\it_0985.txt
Writing short_paragraphs\it\it_0986.txt
Writing short_paragraphs\it\it_0987.txt
Writing short_paragraphs\it\it_0988.txt
Writing short_paragraphs\it\it_0989.txt
Writing short_paragraphs\it\it_0990.txt
Writing short_paragraphs\it\it_0991.txt
Writing short_paragraphs\it\it_0992.txt
Writing short_paragraphs\it\it_0993.txt
Writing paragraphs\it\it_0062.txt
Writing short_paragraphs\it\it_0994.txt
Writing short_paragraphs\it\it_0995.txt
Writing short_paragraphs\it\it_0996.txt
Writing shor

Writing short_paragraphs\nl\nl_0074.txt
Writing short_paragraphs\nl\nl_0075.txt
Writing short_paragraphs\nl\nl_0076.txt
Writing short_paragraphs\nl\nl_0077.txt
Writing short_paragraphs\nl\nl_0078.txt
Writing short_paragraphs\nl\nl_0079.txt
Writing short_paragraphs\nl\nl_0080.txt
Writing short_paragraphs\nl\nl_0081.txt
Writing short_paragraphs\nl\nl_0082.txt
Writing short_paragraphs\nl\nl_0083.txt
Writing short_paragraphs\nl\nl_0084.txt
Writing short_paragraphs\nl\nl_0085.txt
Writing short_paragraphs\nl\nl_0086.txt
Writing short_paragraphs\nl\nl_0087.txt
Writing short_paragraphs\nl\nl_0088.txt
Writing short_paragraphs\nl\nl_0089.txt
Writing short_paragraphs\nl\nl_0090.txt
Writing short_paragraphs\nl\nl_0091.txt
Writing short_paragraphs\nl\nl_0092.txt
Writing short_paragraphs\nl\nl_0093.txt
Writing short_paragraphs\nl\nl_0094.txt
Writing short_paragraphs\nl\nl_0095.txt
Writing short_paragraphs\nl\nl_0096.txt
Writing short_paragraphs\nl\nl_0097.txt
Writing short_paragraphs\nl\nl_0098.txt


Writing short_paragraphs\nl\nl_0270.txt
Writing short_paragraphs\nl\nl_0271.txt
Writing short_paragraphs\nl\nl_0272.txt
Writing short_paragraphs\nl\nl_0273.txt
Writing paragraphs\nl\nl_0021.txt
Writing short_paragraphs\nl\nl_0274.txt
Writing short_paragraphs\nl\nl_0275.txt
Writing short_paragraphs\nl\nl_0276.txt
Writing short_paragraphs\nl\nl_0277.txt
Writing short_paragraphs\nl\nl_0278.txt
Writing short_paragraphs\nl\nl_0279.txt
Writing paragraphs\nl\nl_0022.txt
Writing short_paragraphs\nl\nl_0280.txt
Writing short_paragraphs\nl\nl_0281.txt
Writing short_paragraphs\nl\nl_0282.txt
Writing short_paragraphs\nl\nl_0283.txt
Writing short_paragraphs\nl\nl_0284.txt
Writing short_paragraphs\nl\nl_0285.txt
Writing short_paragraphs\nl\nl_0286.txt
Writing short_paragraphs\nl\nl_0287.txt
Writing short_paragraphs\nl\nl_0288.txt
Writing short_paragraphs\nl\nl_0289.txt
Writing short_paragraphs\nl\nl_0290.txt
Writing short_paragraphs\nl\nl_0291.txt
Writing short_paragraphs\nl\nl_0292.txt
Writing shor

Writing short_paragraphs\nl\nl_0464.txt
Writing short_paragraphs\nl\nl_0465.txt
Writing short_paragraphs\nl\nl_0466.txt
Writing short_paragraphs\nl\nl_0467.txt
Writing short_paragraphs\nl\nl_0468.txt
Writing short_paragraphs\nl\nl_0469.txt
Writing short_paragraphs\nl\nl_0470.txt
Writing short_paragraphs\nl\nl_0471.txt
Writing short_paragraphs\nl\nl_0472.txt
Writing short_paragraphs\nl\nl_0473.txt
Writing short_paragraphs\nl\nl_0474.txt
Writing short_paragraphs\nl\nl_0475.txt
Writing short_paragraphs\nl\nl_0476.txt
Writing short_paragraphs\nl\nl_0477.txt
Writing short_paragraphs\nl\nl_0478.txt
Writing paragraphs\nl\nl_0037.txt
Writing short_paragraphs\nl\nl_0479.txt
Writing short_paragraphs\nl\nl_0480.txt
Writing short_paragraphs\nl\nl_0481.txt
Writing short_paragraphs\nl\nl_0482.txt
Writing short_paragraphs\nl\nl_0483.txt
Writing short_paragraphs\nl\nl_0484.txt
Writing short_paragraphs\nl\nl_0485.txt
Writing short_paragraphs\nl\nl_0486.txt
Writing short_paragraphs\nl\nl_0487.txt
Writin

Writing short_paragraphs\pl\pl_0083.txt
Writing short_paragraphs\pl\pl_0084.txt
Writing short_paragraphs\pl\pl_0085.txt
Writing short_paragraphs\pl\pl_0086.txt
Writing short_paragraphs\pl\pl_0087.txt
Writing short_paragraphs\pl\pl_0088.txt
Writing short_paragraphs\pl\pl_0089.txt
Writing short_paragraphs\pl\pl_0090.txt
Writing short_paragraphs\pl\pl_0091.txt
Writing short_paragraphs\pl\pl_0092.txt
Writing paragraphs\pl\pl_0007.txt
Writing short_paragraphs\pl\pl_0093.txt
Writing short_paragraphs\pl\pl_0094.txt
Writing short_paragraphs\pl\pl_0095.txt
Writing short_paragraphs\pl\pl_0096.txt
Writing short_paragraphs\pl\pl_0097.txt
Writing short_paragraphs\pl\pl_0098.txt
Writing short_paragraphs\pl\pl_0099.txt
Writing short_paragraphs\pl\pl_0100.txt
Writing short_paragraphs\pl\pl_0101.txt
Writing short_paragraphs\pl\pl_0102.txt
Writing short_paragraphs\pl\pl_0103.txt
Writing short_paragraphs\pl\pl_0104.txt
Writing short_paragraphs\pl\pl_0105.txt
Writing short_paragraphs\pl\pl_0106.txt
Writin

Writing short_paragraphs\pl\pl_0283.txt
Writing short_paragraphs\pl\pl_0284.txt
Writing short_paragraphs\pl\pl_0285.txt
Writing short_paragraphs\pl\pl_0286.txt
Writing short_paragraphs\pl\pl_0287.txt
Writing short_paragraphs\pl\pl_0288.txt
Writing short_paragraphs\pl\pl_0289.txt
Writing paragraphs\pl\pl_0019.txt
Writing short_paragraphs\pl\pl_0290.txt
Writing short_paragraphs\pl\pl_0291.txt
Writing short_paragraphs\pl\pl_0292.txt
Writing short_paragraphs\pl\pl_0293.txt
Writing short_paragraphs\pl\pl_0294.txt
Writing short_paragraphs\pl\pl_0295.txt
Writing short_paragraphs\pl\pl_0296.txt
Writing short_paragraphs\pl\pl_0297.txt
Writing short_paragraphs\pl\pl_0298.txt
Writing short_paragraphs\pl\pl_0299.txt
Writing paragraphs\pl\pl_0020.txt
Writing short_paragraphs\pl\pl_0300.txt
Writing short_paragraphs\pl\pl_0301.txt
Writing short_paragraphs\pl\pl_0302.txt
Writing short_paragraphs\pl\pl_0303.txt
Writing short_paragraphs\pl\pl_0304.txt
Writing short_paragraphs\pl\pl_0305.txt
Writing shor

Writing short_paragraphs\pl\pl_0477.txt
Writing short_paragraphs\pl\pl_0478.txt
Writing short_paragraphs\pl\pl_0479.txt
Writing short_paragraphs\pl\pl_0480.txt
Writing short_paragraphs\pl\pl_0481.txt
Writing short_paragraphs\pl\pl_0482.txt
Writing short_paragraphs\pl\pl_0483.txt
Writing short_paragraphs\pl\pl_0484.txt
Writing short_paragraphs\pl\pl_0485.txt
Writing short_paragraphs\pl\pl_0486.txt
Writing short_paragraphs\pl\pl_0487.txt
Writing paragraphs\pl\pl_0033.txt
Writing short_paragraphs\pl\pl_0488.txt
Writing short_paragraphs\pl\pl_0489.txt
Writing short_paragraphs\pl\pl_0490.txt
Writing short_paragraphs\pl\pl_0491.txt
Writing short_paragraphs\pl\pl_0492.txt
Writing short_paragraphs\pl\pl_0493.txt
Writing short_paragraphs\pl\pl_0494.txt
Writing short_paragraphs\pl\pl_0495.txt
Writing short_paragraphs\pl\pl_0496.txt
Writing short_paragraphs\pl\pl_0497.txt
Writing short_paragraphs\pl\pl_0498.txt
Writing short_paragraphs\pl\pl_0499.txt
Writing short_paragraphs\pl\pl_0500.txt
Writin

Writing short_paragraphs\pt\pt_0071.txt
Writing short_paragraphs\pt\pt_0072.txt
Writing short_paragraphs\pt\pt_0073.txt
Writing short_paragraphs\pt\pt_0074.txt
Writing short_paragraphs\pt\pt_0075.txt
Writing short_paragraphs\pt\pt_0076.txt
Writing short_paragraphs\pt\pt_0077.txt
Writing short_paragraphs\pt\pt_0078.txt
Writing short_paragraphs\pt\pt_0079.txt
Writing short_paragraphs\pt\pt_0080.txt
Writing short_paragraphs\pt\pt_0081.txt
Writing short_paragraphs\pt\pt_0082.txt
Writing paragraphs\pt\pt_0003.txt
Writing short_paragraphs\pt\pt_0083.txt
Writing short_paragraphs\pt\pt_0084.txt
Writing short_paragraphs\pt\pt_0085.txt
Writing short_paragraphs\pt\pt_0086.txt
Writing short_paragraphs\pt\pt_0087.txt
Writing short_paragraphs\pt\pt_0088.txt
Writing short_paragraphs\pt\pt_0089.txt
Writing short_paragraphs\pt\pt_0090.txt
Writing short_paragraphs\pt\pt_0091.txt
Writing short_paragraphs\pt\pt_0092.txt
Writing short_paragraphs\pt\pt_0093.txt
Writing short_paragraphs\pt\pt_0094.txt
Writin

Writing short_paragraphs\pt\pt_0269.txt
Writing short_paragraphs\pt\pt_0270.txt
Writing short_paragraphs\pt\pt_0271.txt
Writing short_paragraphs\pt\pt_0272.txt
Writing short_paragraphs\pt\pt_0273.txt
Writing short_paragraphs\pt\pt_0274.txt
Writing short_paragraphs\pt\pt_0275.txt
Writing short_paragraphs\pt\pt_0276.txt
Writing short_paragraphs\pt\pt_0277.txt
Writing short_paragraphs\pt\pt_0278.txt
Writing short_paragraphs\pt\pt_0279.txt
Writing short_paragraphs\pt\pt_0280.txt
Writing short_paragraphs\pt\pt_0281.txt
Writing short_paragraphs\pt\pt_0282.txt
Writing paragraphs\pt\pt_0015.txt
Writing short_paragraphs\pt\pt_0283.txt
Writing short_paragraphs\pt\pt_0284.txt
Writing short_paragraphs\pt\pt_0285.txt
Writing short_paragraphs\pt\pt_0286.txt
Writing short_paragraphs\pt\pt_0287.txt
Writing short_paragraphs\pt\pt_0288.txt
Writing short_paragraphs\pt\pt_0289.txt
Writing short_paragraphs\pt\pt_0290.txt
Writing short_paragraphs\pt\pt_0291.txt
Writing short_paragraphs\pt\pt_0292.txt
Writin

Writing short_paragraphs\pt\pt_0477.txt
Writing short_paragraphs\pt\pt_0478.txt
Writing short_paragraphs\pt\pt_0479.txt
Writing short_paragraphs\pt\pt_0480.txt
Writing short_paragraphs\pt\pt_0481.txt
Writing short_paragraphs\pt\pt_0482.txt
Writing short_paragraphs\pt\pt_0483.txt
Writing short_paragraphs\pt\pt_0484.txt
Writing short_paragraphs\pt\pt_0485.txt
Writing short_paragraphs\pt\pt_0486.txt
Writing short_paragraphs\pt\pt_0487.txt
Writing short_paragraphs\pt\pt_0488.txt
Writing paragraphs\pt\pt_0022.txt
Writing short_paragraphs\pt\pt_0489.txt
Writing short_paragraphs\pt\pt_0490.txt
Writing short_paragraphs\pt\pt_0491.txt
Writing short_paragraphs\pt\pt_0492.txt
Writing short_paragraphs\pt\pt_0493.txt
Writing short_paragraphs\pt\pt_0494.txt
Writing short_paragraphs\pt\pt_0495.txt
Writing short_paragraphs\pt\pt_0496.txt
Writing short_paragraphs\pt\pt_0497.txt
Writing short_paragraphs\pt\pt_0498.txt
Writing short_paragraphs\pt\pt_0499.txt
Writing short_paragraphs\pt\pt_0500.txt
Writin

Writing short_paragraphs\pt\pt_0683.txt
Writing short_paragraphs\pt\pt_0684.txt
Writing paragraphs\pt\pt_0032.txt
Writing short_paragraphs\pt\pt_0685.txt
Writing short_paragraphs\pt\pt_0686.txt
Writing short_paragraphs\pt\pt_0687.txt
Writing short_paragraphs\pt\pt_0688.txt
Writing short_paragraphs\pt\pt_0689.txt
Writing paragraphs\pt\pt_0033.txt
Writing short_paragraphs\pt\pt_0690.txt
Writing short_paragraphs\pt\pt_0691.txt
Writing short_paragraphs\pt\pt_0692.txt
Writing short_paragraphs\pt\pt_0693.txt
Writing short_paragraphs\pt\pt_0694.txt
Writing short_paragraphs\pt\pt_0695.txt
Writing short_paragraphs\pt\pt_0696.txt
Writing short_paragraphs\pt\pt_0697.txt
Writing short_paragraphs\pt\pt_0698.txt
Writing short_paragraphs\pt\pt_0699.txt
Writing short_paragraphs\pt\pt_0700.txt
Writing short_paragraphs\pt\pt_0701.txt
Writing short_paragraphs\pt\pt_0702.txt
Writing short_paragraphs\pt\pt_0703.txt
Writing short_paragraphs\pt\pt_0704.txt
Writing short_paragraphs\pt\pt_0705.txt
Writing shor

Writing short_paragraphs\pt\pt_0880.txt
Writing short_paragraphs\pt\pt_0881.txt
Writing short_paragraphs\pt\pt_0882.txt
Writing short_paragraphs\pt\pt_0883.txt
Writing short_paragraphs\pt\pt_0884.txt
Writing short_paragraphs\pt\pt_0885.txt
Writing short_paragraphs\pt\pt_0886.txt
Writing short_paragraphs\pt\pt_0887.txt
Writing short_paragraphs\pt\pt_0888.txt
Writing short_paragraphs\pt\pt_0889.txt
Writing short_paragraphs\pt\pt_0890.txt
Writing short_paragraphs\pt\pt_0891.txt
Writing short_paragraphs\pt\pt_0892.txt
Writing short_paragraphs\pt\pt_0893.txt
Writing short_paragraphs\pt\pt_0894.txt
Writing short_paragraphs\pt\pt_0895.txt
Writing short_paragraphs\pt\pt_0896.txt
Writing short_paragraphs\pt\pt_0897.txt
Writing short_paragraphs\pt\pt_0898.txt
Writing short_paragraphs\pt\pt_0899.txt
Writing short_paragraphs\pt\pt_0900.txt
Writing short_paragraphs\pt\pt_0901.txt
Writing short_paragraphs\pt\pt_0902.txt
Writing short_paragraphs\pt\pt_0903.txt
Writing short_paragraphs\pt\pt_0904.txt


Writing short_paragraphs\pt\pt_1045.txt
Writing paragraphs\pt\pt_0094.txt
Writing short_paragraphs\pt\pt_1046.txt
Writing paragraphs\pt\pt_0095.txt
Writing short_paragraphs\pt\pt_1047.txt
Writing paragraphs\pt\pt_0096.txt
Writing short_paragraphs\pt\pt_1048.txt
Writing paragraphs\pt\pt_0097.txt
Writing short_paragraphs\pt\pt_1049.txt
Writing paragraphs\pt\pt_0098.txt
Writing short_paragraphs\pt\pt_1050.txt
Writing paragraphs\pt\pt_0099.txt
Writing short_paragraphs\pt\pt_1051.txt
Writing paragraphs\pt\pt_0100.txt
Writing short_paragraphs\pt\pt_1052.txt
Writing paragraphs\pt\pt_0101.txt
Writing short_paragraphs\pt\pt_1053.txt
Writing paragraphs\pt\pt_0102.txt
Writing short_paragraphs\pt\pt_1054.txt
Writing paragraphs\ru\ru_0000.txt
Writing short_paragraphs\ru\ru_0000.txt
Writing short_paragraphs\ru\ru_0001.txt
Writing short_paragraphs\ru\ru_0002.txt
Writing short_paragraphs\ru\ru_0003.txt
Writing paragraphs\ru\ru_0001.txt
Writing short_paragraphs\ru\ru_0004.txt
Writing short_paragraphs\r

Writing short_paragraphs\ru\ru_0179.txt
Writing short_paragraphs\ru\ru_0180.txt
Writing short_paragraphs\ru\ru_0181.txt
Writing short_paragraphs\ru\ru_0182.txt
Writing short_paragraphs\ru\ru_0183.txt
Writing short_paragraphs\ru\ru_0184.txt
Writing short_paragraphs\ru\ru_0185.txt
Writing short_paragraphs\ru\ru_0186.txt
Writing short_paragraphs\ru\ru_0187.txt
Writing short_paragraphs\ru\ru_0188.txt
Writing short_paragraphs\ru\ru_0189.txt
Writing short_paragraphs\ru\ru_0190.txt
Writing short_paragraphs\ru\ru_0191.txt
Writing short_paragraphs\ru\ru_0192.txt
Writing short_paragraphs\ru\ru_0193.txt
Writing paragraphs\ru\ru_0014.txt
Writing short_paragraphs\ru\ru_0194.txt
Writing short_paragraphs\ru\ru_0195.txt
Writing short_paragraphs\ru\ru_0196.txt
Writing short_paragraphs\ru\ru_0197.txt
Writing short_paragraphs\ru\ru_0198.txt
Writing short_paragraphs\ru\ru_0199.txt
Writing short_paragraphs\ru\ru_0200.txt
Writing short_paragraphs\ru\ru_0201.txt
Writing short_paragraphs\ru\ru_0202.txt
Writin

Writing short_paragraphs\ru\ru_0376.txt
Writing short_paragraphs\ru\ru_0377.txt
Writing short_paragraphs\ru\ru_0378.txt
Writing short_paragraphs\ru\ru_0379.txt
Writing short_paragraphs\ru\ru_0380.txt
Writing short_paragraphs\ru\ru_0381.txt
Writing short_paragraphs\ru\ru_0382.txt
Writing short_paragraphs\ru\ru_0383.txt
Writing paragraphs\ru\ru_0024.txt
Writing short_paragraphs\ru\ru_0384.txt
Writing short_paragraphs\ru\ru_0385.txt
Writing short_paragraphs\ru\ru_0386.txt
Writing short_paragraphs\ru\ru_0387.txt
Writing short_paragraphs\ru\ru_0388.txt
Writing short_paragraphs\ru\ru_0389.txt
Writing short_paragraphs\ru\ru_0390.txt
Writing short_paragraphs\ru\ru_0391.txt
Writing short_paragraphs\ru\ru_0392.txt
Writing short_paragraphs\ru\ru_0393.txt
Writing short_paragraphs\ru\ru_0394.txt
Writing short_paragraphs\ru\ru_0395.txt
Writing short_paragraphs\ru\ru_0396.txt
Writing short_paragraphs\ru\ru_0397.txt
Writing short_paragraphs\ru\ru_0398.txt
Writing short_paragraphs\ru\ru_0399.txt
Writin

Writing short_paragraphs\ru\ru_0569.txt
Writing short_paragraphs\ru\ru_0570.txt
Writing short_paragraphs\ru\ru_0571.txt
Writing short_paragraphs\ru\ru_0572.txt
Writing short_paragraphs\ru\ru_0573.txt
Writing short_paragraphs\ru\ru_0574.txt
Writing short_paragraphs\ru\ru_0575.txt
Writing short_paragraphs\ru\ru_0576.txt
Writing paragraphs\ru\ru_0039.txt
Writing short_paragraphs\ru\ru_0577.txt
Writing short_paragraphs\ru\ru_0578.txt
Writing short_paragraphs\ru\ru_0579.txt
Writing short_paragraphs\ru\ru_0580.txt
Writing short_paragraphs\ru\ru_0581.txt
Writing short_paragraphs\ru\ru_0582.txt
Writing short_paragraphs\ru\ru_0583.txt
Writing short_paragraphs\ru\ru_0584.txt
Writing short_paragraphs\ru\ru_0585.txt
Writing short_paragraphs\ru\ru_0586.txt
Writing short_paragraphs\ru\ru_0587.txt
Writing short_paragraphs\ru\ru_0588.txt
Writing paragraphs\ru\ru_0040.txt
Writing short_paragraphs\ru\ru_0589.txt
Writing short_paragraphs\ru\ru_0590.txt
Writing short_paragraphs\ru\ru_0591.txt
Writing shor

Writing short_paragraphs\ru\ru_0767.txt
Writing short_paragraphs\ru\ru_0768.txt
Writing short_paragraphs\ru\ru_0769.txt
Writing short_paragraphs\ru\ru_0770.txt
Writing short_paragraphs\ru\ru_0771.txt
Writing short_paragraphs\ru\ru_0772.txt
Writing short_paragraphs\ru\ru_0773.txt
Writing short_paragraphs\ru\ru_0774.txt
Writing short_paragraphs\ru\ru_0775.txt
Writing short_paragraphs\ru\ru_0776.txt
Writing short_paragraphs\ru\ru_0777.txt
Writing paragraphs\ru\ru_0053.txt
Writing short_paragraphs\ru\ru_0778.txt
Writing short_paragraphs\ru\ru_0779.txt
Writing short_paragraphs\ru\ru_0780.txt
Writing short_paragraphs\ru\ru_0781.txt
Writing short_paragraphs\ru\ru_0782.txt
Writing short_paragraphs\ru\ru_0783.txt
Writing short_paragraphs\ru\ru_0784.txt
Writing short_paragraphs\ru\ru_0785.txt
Writing short_paragraphs\ru\ru_0786.txt
Writing short_paragraphs\ru\ru_0787.txt
Writing short_paragraphs\ru\ru_0788.txt
Writing short_paragraphs\ru\ru_0789.txt
Writing short_paragraphs\ru\ru_0790.txt
Writin

Writing paragraphs\zh\zh_0024.txt
Writing paragraphs\zh\zh_0025.txt
Writing paragraphs\zh\zh_0026.txt
Writing paragraphs\zh\zh_0027.txt
Writing paragraphs\zh\zh_0028.txt
Writing paragraphs\zh\zh_0029.txt
Writing paragraphs\zh\zh_0030.txt
Writing paragraphs\zh\zh_0031.txt
Writing paragraphs\zh\zh_0032.txt
Writing paragraphs\zh\zh_0033.txt
Writing paragraphs\zh\zh_0034.txt
Writing paragraphs\zh\zh_0035.txt
Writing paragraphs\zh\zh_0036.txt
Writing paragraphs\zh\zh_0037.txt
Writing paragraphs\zh\zh_0038.txt
Writing paragraphs\zh\zh_0039.txt
Writing paragraphs\zh\zh_0040.txt
Writing paragraphs\zh\zh_0041.txt
Writing paragraphs\zh\zh_0042.txt
Writing paragraphs\zh\zh_0043.txt
Writing paragraphs\zh\zh_0044.txt
Writing paragraphs\zh\zh_0045.txt
Writing paragraphs\zh\zh_0046.txt
Writing paragraphs\zh\zh_0047.txt
Writing paragraphs\zh\zh_0048.txt
Writing paragraphs\zh\zh_0049.txt
Writing paragraphs\zh\zh_0050.txt
Writing paragraphs\zh\zh_0051.txt
Writing paragraphs\zh\zh_0052.txt
Writing paragr

In [109]:

# simple python script to collect text paragraphs from various languages on the
# same topic namely the Wikipedia encyclopedia itself

import os
try:
    # Python 2 compat
    from urllib2 import Request, build_opener
except ImportError:
    # Python 3
    from urllib.request import Request, build_opener

import lxml.html
from lxml.etree import ElementTree
import numpy as np

import codecs

pages = {
    u'pokemon': u'https://en.wikipedia.org/wiki/List_of_Pok%C3%A9mon',
    u'animal': u'https://en.wikipedia.org/wiki/List_of_animal_names',
}

html_folder = u'datafornoah/phtml'
text_folder = u'datafornoah/pparagraphs'
short_text_folder = u'datafornoah/pshort_paragraphs'
n_words_per_short_text = 5


if not os.path.exists(html_folder):
    os.makedirs(html_folder)

for lang, page in pages.items():

    text_lang_folder = os.path.join(text_folder, lang)
    if not os.path.exists(text_lang_folder):
        os.makedirs(text_lang_folder)

    short_text_lang_folder = os.path.join(short_text_folder, lang)
    if not os.path.exists(short_text_lang_folder):
        os.makedirs(short_text_lang_folder)

    opener = build_opener()
    html_filename = os.path.join(html_folder, lang + '.html')
    if not os.path.exists(html_filename):
        print("Downloading %s" % page)
        request = Request(page)
        # change the User Agent to avoid being blocked by Wikipedia
        # downloading a couple of articles should not be considered abusive
        request.add_header('User-Agent', 'OpenAnything/1.0')
        html_content = opener.open(request).read()
        open(html_filename, 'wb').write(html_content)

    # decode the payload explicitly as UTF-8 since lxml is confused for some
    # reason
    with codecs.open(html_filename,'r','utf-8') as html_file:
        html_content = html_file.read()
    tree = ElementTree(lxml.html.document_fromstring(html_content))
    i = 0
    j = 0
    for p in tree.findall('//p'):
        content = p.text_content()
        if len(content) < 100:
            # skip paragraphs that are too short - probably too noisy and not
            # representative of the actual language
            continue

        text_filename = os.path.join(text_lang_folder,
                                     '%s_%04d.txt' % (lang, i))
        print("Writing %s" % text_filename)
        open(text_filename, 'wb').write(content.encode('utf-8', 'ignore'))
        i += 1

        # split the paragraph into fake smaller paragraphs to make the
        # problem harder e.g. more similar to tweets
        if lang in ('zh', 'ja'):
        # FIXME: whitespace tokenizing does not work on chinese and japanese
            continue
        words = content.split()
        n_groups = len(words) / n_words_per_short_text
        if n_groups < 1:
            continue
        groups = np.array_split(words, n_groups)

        for group in groups:
            small_content = u" ".join(group)

            short_text_filename = os.path.join(short_text_lang_folder,
                                               '%s_%04d.txt' % (lang, j))
            print("Writing %s" % short_text_filename)
            open(short_text_filename, 'wb').write(
                small_content.encode('utf-8', 'ignore'))
            j += 1
            if j >= 1000:
                break

import os

Writing datafornoah/pparagraphs\pokemon\pokemon_0000.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0000.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0001.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0002.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0003.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0004.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0005.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0006.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0007.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0008.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0009.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0010.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0011.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0012.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0013.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0014.tx

Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0127.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0128.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0129.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0130.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0131.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0132.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0133.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0134.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0135.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0136.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0137.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0138.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0139.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0140.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0141.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0

Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0257.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0258.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0259.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0260.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0261.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0262.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0263.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0264.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0265.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0266.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0267.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0268.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0269.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0270.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0271.txt
Writing datafornoah/pshort_paragraphs\pokemon\pokemon_0

In [110]:
fn = os.listdir("datafornoah/")
fil = []
for folder in fn:
    sss = os.listdir("datafornoah/" + folder)
    if folder == "html":
        for subfold in sss:
            fil.append("datafornoah/" + folder + "/" + subfold)
    else:
        for subfold in sss:
            fff = os.listdir("datafornoah/" + folder + "/" + subfold + "/")
            for file in fff:
                fil.append("datafornoah/" + folder + "/" + subfold + "/" + file)
#filenames = ["datafornoah/paragraphs/ar/ar_0000.txt", "datafornoah/paragraphs/ar/ar_0001.txt"]
#for fname in filenames:
#    with open(fname, 'r', encoding="utf8") as fin:
#        print(fin.read())
print(len(fil))

NotADirectoryError: [WinError 267] The directory name is invalid: 'datafornoah/phtml/pokemon.html/'

In [ ]:
%run workspace/exercise_01_language_train_model.py data/languages/paragraphs/

In [ ]:
languages_data_folder = "datafornoah"#sys.argv[1]
dataset = load_files(languages_data_folder, encoding="utf8")
#for fname in fil:
#    with open(fname, 'r', encoding="utf8") as fin:
#        dataset.append(fin.read())
#figure out the cause of this permissions error

In [ ]:
len(dataset)

In [ ]:
docs_train, docs_test, y_train, y_test = train_test_split(
    dataset.data, dataset.target, test_size=0.5)

In [ ]:
#this error continued to persist

In [ ]:
# Chris came up with a solution whereby I run the code from a python file in an ipython console directly

In [ ]:
# there is another file that has the rest of the code for this example. It is also on GitHub.

In [ ]:
print("Thanks again for the great class! :)")