In [1]:
from sklearn import datasets
iris = datasets.load_iris()
digits = datasets.load_digits()

In [2]:
print(digits.data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [3]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [4]:
digits.images[0]

array([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.],
       [ 0.,  0., 13., 15., 10., 15.,  5.,  0.],
       [ 0.,  3., 15.,  2.,  0., 11.,  8.,  0.],
       [ 0.,  4., 12.,  0.,  0.,  8.,  8.,  0.],
       [ 0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.],
       [ 0.,  4., 11.,  0.,  1., 12.,  7.,  0.],
       [ 0.,  2., 14.,  5., 10., 12.,  0.,  0.],
       [ 0.,  0.,  6., 13., 10.,  0.,  0.,  0.]])

In [5]:
print(type(iris))
print(type(digits))

<class 'sklearn.utils.Bunch'>
<class 'sklearn.utils.Bunch'>


In [6]:
from sklearn import svm

In [7]:
clf = svm.SVC(gamma=0.001, C=100.)

In [8]:
clf.fit(digits.data[:-1], digits.target[:-1])


SVC(C=100.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [9]:
clf.predict(digits.data[-1:])

array([8])

In [10]:
clf = svm.SVC()

In [11]:
X, y = iris.data, iris.target

In [12]:
clf.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [13]:
import pickle

In [14]:
s = pickle.dumps(clf)

In [15]:
clf2 = pickle.loads(s)

In [16]:
clf2.predict(X[0:1])

array([0])

In [17]:
y[0]

0

In [18]:
from sklearn.externals import joblib

In [19]:
joblib.dump(clf, 'filename.pkl')

['filename.pkl']

In [20]:
clf = joblib.load('filename.pkl')

In [21]:
import numpy as np

In [22]:
from sklearn import random_projection

In [23]:
rng = np.random.RandomState(0)

In [24]:
X = rng.rand(10, 2000)

In [25]:
X = np.array(X, dtype='float32')

In [26]:
X.dtype

dtype('float32')

In [27]:
transformer = random_projection.GaussianRandomProjection()
X_new = transformer.fit_transform(X)

In [28]:
X_new.dtype

dtype('float64')

In [29]:
from sklearn.svm import SVC

In [30]:
clf = SVC()

In [31]:
clf.fit(iris.data, iris.target)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [32]:
list(clf.predict(iris.data[:3]))

[0, 0, 0]

In [33]:
clf.fit(iris.data, iris.target_names[iris.target])

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [34]:
list(clf.predict(iris.data[:3]))

['setosa', 'setosa', 'setosa']

In [35]:
rng = np.random.RandomState(0)

In [36]:
X = rng.rand(100, 10)

In [37]:
y = rng.binomial (1, .5, 100)

In [38]:
X_test = rng.rand(5, 10)

In [39]:
clf = SVC()

In [40]:
clf.set_params(kernel='linear').fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [41]:
clf.predict(X_test)

array([1, 0, 1, 1, 0])

In [42]:
 clf.set_params(kernel='rbf').fit(X, y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [43]:
clf.predict(X_test)

array([0, 0, 0, 1, 0])

In [44]:
from sklearn.multiclass import OneVsRestClassifier

In [45]:
from sklearn.preprocessing import LabelBinarizer

In [46]:
X = [[1, 2], [2, 4], [4, 5], [3, 2], [3, 1]]

In [47]:
y = [0, 0, 1, 1, 2]


In [48]:
classif = OneVsRestClassifier(estimator=SVC(random_state=0))

In [49]:
classif.fit(X, y).predict(X)

array([0, 0, 1, 1, 2])

In [50]:
y = LabelBinarizer().fit_transform(y)

In [51]:
classif.fit(X, y).predict(X)

array([[1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [52]:
 from sklearn.preprocessing import MultiLabelBinarizer

In [53]:
y = [[0, 1], [0, 2], [1, 3], [0, 2, 3], [2, 4]]

In [54]:
y = MultiLabelBinarizer().fit_transform(y)

In [55]:
classif.fit(X, y).predict(X)

array([[1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0]])

In [56]:
# End of introductory tutorial

In [57]:
categories = ['alt.atheism', 'soc.religion.christian','comp.graphics', 'sci.med']

In [58]:
from sklearn.datasets import fetch_20newsgroups

In [59]:
twenty_train = fetch_20newsgroups(subset='train', categories=categories, shuffle=True, random_state=42)

In [60]:
twenty_train.target_names

['alt.atheism', 'comp.graphics', 'sci.med', 'soc.religion.christian']

In [61]:
len(twenty_train.data)

2257

In [62]:
len(twenty_train.filenames)

2257

In [63]:
print("\n".join(twenty_train.data[2].split("\n")[:3]))

From: djohnson@cs.ucsd.edu (Darin Johnson)
Subject: Re: harrassed at work, could use some prayers
Organization: =CSE Dept., U.C. San Diego


In [64]:
print(twenty_train.target_names[twenty_train.target[2]])

soc.religion.christian


In [65]:
twenty_train.target[:10]

array([1, 1, 3, 3, 3, 3, 3, 2, 2, 2], dtype=int64)

In [66]:
for t in twenty_train.target[:10]:print(twenty_train.target_names[t])

comp.graphics
comp.graphics
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
soc.religion.christian
sci.med
sci.med
sci.med


In [67]:
twenty_train.data[68]

'From: revdak@netcom.com (D. Andrew Kille)\nSubject: Re: Easter: what\'s in a name? (was Re: New Testament Double Stan\nOrganization: NETCOM On-line Communication Services (408 241-9760 guest)\nLines: 40\n\nDaniel Segard (dsegard@nyx.cs.du.edu) wrote:\n\n[a lot of stuff deleted]\n\n:      For that matter, stay Biblical and call it Omar Rasheet (The Feast of\n: First Fruits).  Torah commands that this be observed on the day following\n: the Sabbath of Passover week.  (Sunday by any other name in modern\n: parlance.)  Why is there so much objection to observing the Resurrection\n: on the 1st day of the week on which it actually occured?  Why jump it all\n: over the calendar the way Easter does?  Why not just go with the Sunday\n: following Passover the way the Bible has it?  Why seek after unbiblical\n: methods?\n:  \nIn fact, that is the reason Easter "jumps all over the calendar"- Passsover\nitself is a lunar holiday, not a solar one, and thus falls over a wide\npossible span of times.

In [68]:
from sklearn.feature_extraction.text import CountVectorizer

In [69]:
count_vect = CountVectorizer()

In [70]:
X_train_counts = count_vect.fit_transform(twenty_train.data)

In [71]:
X_train_counts.shape

(2257, 35788)

In [72]:
 count_vect.vocabulary_.get(u'algorithm')

4690

In [73]:
# yo that's dope

In [74]:
from sklearn.feature_extraction.text import TfidfTransformer
tf_transformer = TfidfTransformer(use_idf=False).fit(X_train_counts)
X_train_tf = tf_transformer.transform(X_train_counts)
X_train_tf.shape

(2257, 35788)

In [75]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

(2257, 35788)

In [76]:
from sklearn.naive_bayes import MultinomialNB

In [77]:
clf = MultinomialNB().fit(X_train_tfidf, twenty_train.target)

In [78]:
docs_new = ['God is love', 'OpenGL on the GPU is fast']

In [79]:
X_new_counts = count_vect.transform(docs_new)

In [80]:
X_new_tfidf = tfidf_transformer.transform(X_new_counts)

In [81]:
predicted = clf.predict(X_new_tfidf)

In [82]:
for doc, category in zip(docs_new, predicted):
    print('%r => %s' % (doc, twenty_train.target_names[category]))

'God is love' => soc.religion.christian
'OpenGL on the GPU is fast' => comp.graphics


In [83]:
from sklearn.pipeline import Pipeline

In [84]:
text_clf = Pipeline([('vect', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('clf', MultinomialNB()),
 ])

In [85]:
text_clf.fit(twenty_train.data, twenty_train.target)

Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...inear_tf=False, use_idf=True)), ('clf', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [136]:
twenty_test = fetch_20newsgroups(subset='test',
     categories=categories, shuffle=True, random_state=42)
#print(twenty_test)

In [87]:
docs_test = twenty_test.data

In [88]:
predicted = text_clf.predict(docs_test)

In [89]:
np.mean(predicted == twenty_test.target)            


0.8348868175765646

In [90]:
from sklearn.linear_model import SGDClassifier

In [91]:
text_clf = Pipeline([('vect', CountVectorizer()),
                      ('tfidf', TfidfTransformer()),
                      ('clf', SGDClassifier(loss='hinge', penalty='l2',
                                            alpha=1e-3, random_state=42,
                                            max_iter=5, tol=None)),
 ])

In [92]:
text_clf.fit(twenty_train.data, twenty_train.target) 

Pipeline(memory=None,
     steps=[('vect', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip...ty='l2', power_t=0.5, random_state=42, shuffle=True,
       tol=None, verbose=0, warm_start=False))])

In [93]:
predicted = text_clf.predict(docs_test)

In [94]:
np.mean(predicted == twenty_test.target)

0.9127829560585885

In [95]:
from sklearn import metrics

In [96]:
# I feel like it's kind of late to be importing metrics...

In [97]:
print(metrics.classification_report(twenty_test.target, predicted,
     target_names=twenty_test.target_names))

                        precision    recall  f1-score   support

           alt.atheism       0.95      0.81      0.87       319
         comp.graphics       0.88      0.97      0.92       389
               sci.med       0.94      0.90      0.92       396
soc.religion.christian       0.90      0.95      0.93       398

           avg / total       0.92      0.91      0.91      1502



In [98]:
metrics.confusion_matrix(twenty_test.target, predicted)

array([[258,  11,  15,  35],
       [  4, 379,   3,   3],
       [  5,  33, 355,   3],
       [  5,  10,   4, 379]], dtype=int64)

In [99]:
from sklearn.model_selection import GridSearchCV

In [100]:
parameters = {'vect__ngram_range': [(1, 1), (1, 2)],
               'tfidf__use_idf': (True, False),
               'clf__alpha': (1e-2, 1e-3),
 }

In [101]:
gs_clf = GridSearchCV(text_clf, parameters, n_jobs=-1)

In [102]:
gs_clf = gs_clf.fit(twenty_train.data[:400], twenty_train.target[:400])

In [103]:
twenty_train.target_names[gs_clf.predict(['Jesus works for HP'])[0]]

'soc.religion.christian'

In [104]:
gs_clf.best_score_  

0.9

In [105]:
for param_name in sorted(parameters.keys()):
     print("%s: %r" % (param_name, gs_clf.best_params_[param_name]))

clf__alpha: 0.001
tfidf__use_idf: True
vect__ngram_range: (1, 1)


In [106]:
# done with tutorials -- moving on to example

In [107]:
import sys

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import Perceptron
from sklearn.pipeline import Pipeline
from sklearn.datasets import load_files
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [138]:

# simple python script to collect text paragraphs from various languages on the
# same topic namely the Wikipedia encyclopedia itself

import os
try:
    # Python 2 compat
    from urllib2 import Request, build_opener
except ImportError:
    # Python 3
    from urllib.request import Request, build_opener

import lxml.html
from lxml.etree import ElementTree
import numpy as np

import codecs

pages = {
    u'ar': u'http://ar.wikipedia.org/wiki/%D9%88%D9%8A%D9%83%D9%8A%D8%A8%D9%8A%D8%AF%D9%8A%D8%A7',
    u'de': u'http://de.wikipedia.org/wiki/Wikipedia',
    u'en': u'https://en.wikipedia.org/wiki/Wikipedia',
    u'es': u'http://es.wikipedia.org/wiki/Wikipedia',
    u'fr': u'http://fr.wikipedia.org/wiki/Wikip%C3%A9dia',
    u'it': u'http://it.wikipedia.org/wiki/Wikipedia',
    u'ja': u'http://ja.wikipedia.org/wiki/Wikipedia',
    u'nl': u'http://nl.wikipedia.org/wiki/Wikipedia',
    u'pl': u'http://pl.wikipedia.org/wiki/Wikipedia',
    u'pt': u'http://pt.wikipedia.org/wiki/Wikip%C3%A9dia',
    u'ru': u'http://ru.wikipedia.org/wiki/%D0%92%D0%B8%D0%BA%D0%B8%D0%BF%D0%B5%D0%B4%D0%B8%D1%8F',
    u'zh': u'http://zh.wikipedia.org/wiki/Wikipedia',
}

html_folder = u'html'
text_folder = u'paragraphs'
short_text_folder = u'short_paragraphs'
n_words_per_short_text = 5


if not os.path.exists(html_folder):
    os.makedirs(html_folder)

for lang, page in pages.items():

    text_lang_folder = os.path.join(text_folder, lang)
    if not os.path.exists(text_lang_folder):
        os.makedirs(text_lang_folder)

    short_text_lang_folder = os.path.join(short_text_folder, lang)
    if not os.path.exists(short_text_lang_folder):
        os.makedirs(short_text_lang_folder)

    opener = build_opener()
    html_filename = os.path.join(html_folder, lang + '.html')
    if not os.path.exists(html_filename):
        print("Downloading %s" % page)
        request = Request(page)
        # change the User Agent to avoid being blocked by Wikipedia
        # downloading a couple of articles should not be considered abusive
        request.add_header('User-Agent', 'OpenAnything/1.0')
        html_content = opener.open(request).read()
        open(html_filename, 'wb').write(html_content)

    # decode the payload explicitly as UTF-8 since lxml is confused for some
    # reason
    with codecs.open(html_filename,'r','utf-8') as html_file:
        html_content = html_file.read()
    tree = ElementTree(lxml.html.document_fromstring(html_content))
    i = 0
    j = 0
    for p in tree.findall('//p'):
        content = p.text_content()
        if len(content) < 100:
            # skip paragraphs that are too short - probably too noisy and not
            # representative of the actual language
            continue

        text_filename = os.path.join(text_lang_folder,
                                     '%s_%04d.txt' % (lang, i))
        print("Writing %s" % text_filename)
        open(text_filename, 'wb').write(content.encode('utf-8', 'ignore'))
        i += 1

        # split the paragraph into fake smaller paragraphs to make the
        # problem harder e.g. more similar to tweets
        if lang in ('zh', 'ja'):
        # FIXME: whitespace tokenizing does not work on chinese and japanese
            continue
        words = content.split()
        n_groups = len(words) / n_words_per_short_text
        if n_groups < 1:
            continue
        groups = np.array_split(words, n_groups)

        for group in groups:
            small_content = u" ".join(group)

            short_text_filename = os.path.join(short_text_lang_folder,
                                               '%s_%04d.txt' % (lang, j))
            print("Writing %s" % short_text_filename)
            open(short_text_filename, 'wb').write(
                small_content.encode('utf-8', 'ignore'))
            j += 1
            if j >= 1000:
                break

import os

Writing paragraphs\ar\ar_0000.txt
Writing short_paragraphs\ar\ar_0000.txt
Writing short_paragraphs\ar\ar_0001.txt
Writing short_paragraphs\ar\ar_0002.txt
Writing short_paragraphs\ar\ar_0003.txt
Writing short_paragraphs\ar\ar_0004.txt
Writing short_paragraphs\ar\ar_0005.txt
Writing short_paragraphs\ar\ar_0006.txt
Writing short_paragraphs\ar\ar_0007.txt
Writing short_paragraphs\ar\ar_0008.txt
Writing short_paragraphs\ar\ar_0009.txt
Writing short_paragraphs\ar\ar_0010.txt
Writing paragraphs\ar\ar_0001.txt
Writing short_paragraphs\ar\ar_0011.txt
Writing short_paragraphs\ar\ar_0012.txt
Writing short_paragraphs\ar\ar_0013.txt
Writing short_paragraphs\ar\ar_0014.txt
Writing short_paragraphs\ar\ar_0015.txt
Writing short_paragraphs\ar\ar_0016.txt
Writing short_paragraphs\ar\ar_0017.txt
Writing short_paragraphs\ar\ar_0018.txt
Writing short_paragraphs\ar\ar_0019.txt
Writing short_paragraphs\ar\ar_0020.txt
Writing short_paragraphs\ar\ar_0021.txt
Writing short_paragraphs\ar\ar_0022.txt
Writing shor

Writing short_paragraphs\ar\ar_0188.txt
Writing short_paragraphs\ar\ar_0189.txt
Writing short_paragraphs\ar\ar_0190.txt
Writing short_paragraphs\ar\ar_0191.txt
Writing short_paragraphs\ar\ar_0192.txt
Writing short_paragraphs\ar\ar_0193.txt
Writing paragraphs\ar\ar_0018.txt
Writing short_paragraphs\ar\ar_0194.txt
Writing short_paragraphs\ar\ar_0195.txt
Writing short_paragraphs\ar\ar_0196.txt
Writing short_paragraphs\ar\ar_0197.txt
Writing short_paragraphs\ar\ar_0198.txt
Writing paragraphs\ar\ar_0019.txt
Writing short_paragraphs\ar\ar_0199.txt
Writing short_paragraphs\ar\ar_0200.txt
Writing short_paragraphs\ar\ar_0201.txt
Writing short_paragraphs\ar\ar_0202.txt
Writing short_paragraphs\ar\ar_0203.txt
Writing short_paragraphs\ar\ar_0204.txt
Writing short_paragraphs\ar\ar_0205.txt
Writing short_paragraphs\ar\ar_0206.txt
Writing paragraphs\ar\ar_0020.txt
Writing short_paragraphs\ar\ar_0207.txt
Writing short_paragraphs\ar\ar_0208.txt
Writing short_paragraphs\ar\ar_0209.txt
Writing short_para

KeyboardInterrupt: 

In [128]:
fn = os.listdir("datafornoah/")
fil = []
for folder in fn:
    sss = os.listdir("datafornoah/" + folder)
    if folder == "html":
        for subfold in sss:
            fil.append("datafornoah/" + folder + "/" + subfold)
    else:
        for subfold in sss:
            fff = os.listdir("datafornoah/" + folder + "/" + subfold + "/")
            for file in fff:
                fil.append("datafornoah/" + folder + "/" + subfold + "/" + file)
#filenames = ["datafornoah/paragraphs/ar/ar_0000.txt", "datafornoah/paragraphs/ar/ar_0001.txt"]
#for fname in filenames:
#    with open(fname, 'r', encoding="utf8") as fin:
#        print(fin.read())
print(len(fil))

9758


In [141]:
%run workspace/exercise_01_language_train_model.py data/languages/paragraphs/

ERROR:root:File `'workspace/exercise_01_language_train_model.py'` not found.


In [133]:
languages_data_folder = "datafornoah"#sys.argv[1]
dataset = load_files(languages_data_folder, encoding="utf8")
#for fname in fil:
#    with open(fname, 'r', encoding="utf8") as fin:
#        dataset.append(fin.read())
#figure out the cause of this permissions error

PermissionError: [Errno 13] Permission denied: 'datafornoah\\paragraphs\\ar'

In [130]:
len(dataset)

9758

In [131]:
docs_train, docs_test, y_train, y_test = train_test_split(
    dataset.data, dataset.target, test_size=0.5)

AttributeError: 'list' object has no attribute 'data'

In [ ]:
#this error continued to persist

In [142]:
# Chris came up with a solution whereby I run the code from a python file in an ipython console directly

In [ ]:
# there is another file that has the rest of the code for this example. It is also on GitHub.

In [143]:
print("Thanks again for the great class! :)")

Thanks again for the great class! :)
